function [all_profiles,profile_names] = saved_profiles()

% Initialize cell array of profiles
all_profiles = cell(0);
profile_names = cell(0);

%% PROFILE 1
profile_name = "System Comparison (ODDM/OTFS/OFDM)";
p = struct;
p.vis_type = "figure";
p.data_type = "BER";
p.primary_var = "EbN0";
p.primary_vals = 3:3:18;
p.default_parameters = struct(...
    'system_name', "ODDM",...
    'CP', false,...
    'receiver_name', "CMC-MMSE",...
    'max_timing_offset', 0.0,...
    'M_ary', 4, ...
    'EbN0', 18, ...
    'M', 64, ...
    'N', 16, ...
    'U', 1, ...
    'T', 1 / 15000, ...
    'Fc', 4e9, ...
    'vel', 500, ...
    'shape', "rrc", ...
    'alpha', 0.4, ...
    'Q', 8);
p.configs = {
    struct('system_name','ODDM','CP',false)
    struct('system_name','ODDM','CP',true)
    struct('system_name','OTFS')
    struct('system_name','OFDM','M',64*16)
    };
p.delete_configs = [];
p.legend_vec = {
    "CP-Free ODDM (Proposed)"
    "CP-ODDM"
    "OTFS"
    "OFDM"
    };
p.line_styles = {
    "-x"
    "-+"
    "-v"
    "-square"
    };
p.line_colors = {...
    "#FF0000"
    "#00FF00"
    "#0000FF"
    "#FF00FF"
    };
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];

%% PROFILE 2
profile_name = "Receiver Comparison (CMC-MMSE/MMSE)";
p = struct;
p.vis_type = "figure";
p.data_type = "t_RXfull";
p.primary_var = "N";
p.primary_vals = 16:16:64;
p.default_parameters = struct(...
    'system_name', "ODDM",...
    'CP', false,...
    'receiver_name', "CMC-MMSE",...
    'max_timing_offset', 0.0,...
    'M_ary', 4, ...
    'EbN0', 18, ...
    'M', 64, ...
    'N', 16, ...
    'U', 1, ...
    'T', 1 / 15000, ...
    'Fc', 4e9, ...
    'vel', 120, ...
    'shape', "rrc", ...
    'alpha', 0.4, ...
    'Q', 8);
p.configs = {
    struct('receiver_name','CMC-MMSE','M',32)
    struct('receiver_name','CMC-MMSE','M',64)
    struct('receiver_name','MMSE','M',32)
    struct('receiver_name','MMSE','M',64)
    };
p.delete_configs = [];
p.legend_vec = {
    "CMC-MMSE, M=32"
    "CMC-MMSE, M=64"
    "MMSE, M=32"
    "MMSE, M=64"
    };
p.line_styles = {
    "-x"
    "--x"
    "-+"
    "--+"
    };
p.line_colors = {...
    "#FF0000"
    "#FF0000"
    "#0000FF"
    "#0000FF"
    };
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];

%% PROFILE 3
profile_name = "Timing Offset Sweep (0:0.25:1 * T_s)";
p = struct;
p.vis_type = "figure";
p.data_type = "BER";
p.primary_var = "max_timing_offset";
p.primary_vals = 0:0.25:1;
p.default_parameters = struct(...
    'system_name', "ODDM",...
    'CP', false,...
    'receiver_name', "CMC-MMSE",...
    'max_timing_offset', 0.0,...
    'M_ary', 4, ...
    'EbN0', 12, ...
    'M', 64, ...
    'N', 64, ...
    'U', 1, ...
    'T', 1 / 15000, ...
    'Fc', 4e9, ...
    'vel', 500, ...
    'shape', "rrc", ...
    'alpha', 0.4, ...
    'Q', 8);
p.configs = {
    struct('M',32,'N',16)
    struct('M',32,'N',64)
    struct('M',64,'N',16)
    struct('M',64,'N',64)
    };
p.delete_configs = [];
p.legend_vec = {
    "M=32,N=16"
    "M=32,N=64"
    "M=64,N=16"
    "M=64,N=64"
    };
p.line_styles = {
    "-x"
    "--x"
    "-+"
    "--+"
    };
p.line_colors = {...
    "#FF0000"
    "#FF0000"
    "#0000FF"
    "#0000FF"
    };
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];