function [all_profiles,profile_names] = saved_profiles()

% Initialize cell array of profiles
all_profiles = cell(0);
profile_names = cell(0);

%% PROFILE 1
profile_name = "CP-Free ODDM SIC-MMSE - Velocity Sweep";
p = struct;
p.primary_var = "EbN0";
p.primary_vals = 4:4:16;
p.default_parameters = struct(...
    'system_name', "ODDM",...
    'CP', false,...
    'receiver_name', "SIC-MMSE",...
    'max_timing_offset', 0.0,...
    'M_ary', 4, ...
    'EbN0', 16, ...
    'M', 64, ...
    'N', 16, ...
    'U', 1, ...
    'T', 1 / 15000, ...
    'Fc', 4e9, ...
    'vel', 40, ...
    'shape', "rrc", ...
    'alpha', 1, ...
    'Q', 2, ...
    'sic_iters', 8);
p.configs = {
    struct('vel',40)
    struct('vel',120)
    struct('vel',500)
    };
p.delete_configs = [];
p.legend_vec = {
    "40 km/hr"
    "120 km/hr"
    "500 km/hr"
    };
p.line_styles = {
    "-bo"
    "-rsquare"
    "-g^"
    };
p.line_colors = {...
    "#0000FF"
    "#FF0000"
    "#00FF00"
    };
p.vis_type = "figure";
p.data_type = "BER";
p.legend_loc = "southwest";
p.ylim_vec = [1e-3 1];
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];
