function [all_profiles,profile_names] = saved_profiles()

% Initialize cell array of profiles
all_profiles = cell(0);
profile_names = cell(0);

%% PROFILE 1
profile_name = "BER Comp, different N and vel";
p = struct;
p.primary_var = "EbN0";
p.primary_vals = 3:3:24;
p.default_parameters = struct(...
    'system_name', "ODDM",...
    'CP', false,...
    'receiver_name', "CMC-MMSE",... 
    'max_timing_offset', 0.0,...
    'M_ary', 4, ...
    'EbN0', 18, ...
    'M', 64, ...
    'N', 16, ...
    'U', 1, ...
    'T', 1 / 15000, ...
    'Fc', 4e9, ...
    'vel', 500, ...
    'shape', "rrc", ...
    'alpha', 0.4, ...
    'Q', 8);
p.configs = {
    struct('N',16,'vel',120)
    struct('N',16,'vel',500)
    };
p.delete_configs = [];
p.legend_vec = {
    "v=120 km/hr"
    "v=500 km/hr"
    };
p.line_styles = {
    "-x"
    "-+"
    };
p.line_colors = {...
    "#FF0000"
    "#0000FF"
    };
p.vis_type = "figure";
p.data_type = "BER";
p.legend_loc = "southwest";
p.ylim_vec = [1e-5 1e-1];
all_profiles = [all_profiles p];
profile_names = [profile_names profile_name];
